name: CI/CD Pipeline

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ .env.DOCKER_HUB_USERNAME }}
          password: ${{ .env.DOCER_HUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build \
          --build-arg BOT_TOKEN=${{.env.BOT_TOKEN}} \
          --build-arg CHAT_ID=${{.env.CHAT_ID}} \
          -t ${{ .env.DOCKER_HUB_USERNAME }}/milfbot:latest .
          
          docker push ${{ .env.DOCKER_HUB_USERNAME }}/milfbot:latest
          
