name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: .env

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build \
          --build-arg BOT_TOKEN=${{secrets.BOT_TOKEN}} \
          --build-arg CHAT_ID=${{secrets.CHAT_ID}} \
          -t ${{ secrets.DOCKER_HUB_USERNAME }}/milfbot:latest .
          
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/milfbot:latest
          
