name: CI/CD Pipeline

on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Print to console
      run: echo Hello
    - name: print two lines
      run: |
        echo First line
        echo Second line
    