name: CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secret.DOCKER_HUB_USERNAME }}
          password: ${{ secret.DOCER_HUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build \
          --build-arg BOT_TOKEN=${{secret.BOT_TOKEN}} \
          --build-arg CHAT_ID=${{secret.CHAT_ID}} \
          -t ${{ secret.DOCKER_HUB_USERNAME }}/milfbot:latest .
          
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/milfbot:latest
          
