name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: .env

    steps:

      - name: checkout code
        uses: actions/checkout@v4

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker build \
          --build-arg BOT_TOKEN=${{secrets.BOT_TOKEN}} \
          --build-arg CHAT_ID=${{secrets.CHAT_ID}} \
          -t ${{ secrets.DOCKER_HUB_USERNAME }}/milfbot:latest ./src
          
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/milfbot:latest
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: .env

    steps:
      - name: Setup SSHpass
        run: sudo apt-get install -y sshpass

      - name: login and deploy
        run: |
          sshpass -p ${{ secrets.SERVER_PASSWORD}} ssh -o StrictHostKeyChecking=no ${{secrets.SERVER_USER}}@${{secrets.SERVER_IP}} << 'EOF'
          cd /home/${{secrets.SERVER_USER }}/MILF_bot
          
          docker stop milfbot || true
          docker rm milfbot || true
          docker rmi -f milfbot || true
          
          docker pull ${{secrets.DOCKER_HUB_USERNAME}}/milfbot:latest
          
          docker run -d --name milfbot --restart unless-stopped ${{ secrets.DOCKER_HUB_USERNAME}}/milfbot:latest
          EOF
        
        
